global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']

  - job_name: 'consul'
    consul_sd_configs:
      - server: 'http://consul:8500'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*
        target_label: tags
      - source_labels: [__meta_consul_service]
        target_label: job
